# Generated by Django 4.0.3 on 2022-03-24 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
