# Generated by Django 4.0.3 on 2022-03-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
