# Generated by Django 4.0.3 on 2022-03-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_user_location_id_delete_location_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='address',
            field=models.CharField(max_length=240),
        ),
    ]
